## Historical Context for Venetian Vostizza {#history}

**TODO - revise and expand text**

Mainland Greece lost all political autonomy in 146 B.C. when the Romans crushed a revolt of the Achaean League and made Greece a dependency.^[**TODO: find out what this is or replace it** CAH3 v. IX, p. 32 states that L. Mummius put down a revolt of the Achaean League in 146 B.C. Afterwards the cities in Greece paid tribute to Rome although Greece did not receive a governor until the late 1st century B.C. (@heurtleyShortHistoryGreece1967, p. 28).] From 146 B.C. until around the time of the Fourth Crusade in the early 13th century, Greece was mostly under Roman and later Byzantine control. From the 580s AD until the early 8th century, Roman rule was disrupted by attacks by Slavs, some of whom settled in Central Greece and the Peloponnese.^[**TODO: find out what this is or replace it** CAH2 v.14, 727; @darbyMedievalTurkishGreece1964, pp. 41-48. Knowledge of Slavic settlement in the Peloponnese comes from the Chronicle of Monemvasia. For the veracity of this document see @charanisChronicleMonemvasiaQuestion1950. The three versions of the text can be found in @beesChroniconMonembasiaeStudy1979.] The Normans had made previous attempts to occupy Greece in the late 12th century.^[@darbyMedievalTurkishGreece1964, p. 51. Failed Norman conquests of Greece include 1081-1084; 1106; 1146; 1185.] After the attack and capture of Constantinople by the Crusaders in 1204, the Byzantine Empire was divided among the Crusaders and their allies.^[Whether the Venetians persuaded the Crusaders to attack Constantinople or the Crusaders had it in mind already is not entirely known. @darbyMedievalTurkishGreece1964, pp. 52-53) is of the opinion that the Venetians persuaded the Crusaders to divert first to Zara and then to Constantinople in order to pay off their passage to the Levant. @mcneillVeniceHingeEurope2009, p. 30 explains that the diversion away from the Holy Land may have had more to do with the personal interests of the commander-in-chief of the Crusaders, Boniface of Montferrat. @lockFranksAegean120415002014, p. 141 notes that the capture of Constantinople was caused by instability in the city, rather than direct Venetian influence. For more information about the Latin states in Greece after the Fourth Crusade see: @darbyMedievalTurkishGreece1964, pp. 52-72; @millerLatinsLevantHistory1908; @lockFranksAegean120415002014.] From this time, various Western European powers (including Franks, Flemings, and Italians, such as the Genoese, Florentines, and Venetians) had possessions in Greece (Fig. 3).^[@toppingFeudalInstitutionsRevealed1949; @toppingRegimeAgraireDans1956; @toppingCrusadersConquerorsChronicle1965; @toppingESTATESNICCOLOACCIAIUOLI1966; @toppingFrankishEstateBay1966; @toppingCoexistenceGreeksLatins1976; @bonMoreeFranqueRecherches1969.]

The Venetians had already obtained influence within the Byzantine Empire by 1082, when the Byzantine Emperor gave them the right of free trade in exchange for help against the Normans.^[@darbyMedievalTurkishGreece1964, p. 51; @mcneillVeniceHingeEurope2009, p. 3. The trade agreement between the Venetians and the Byzantine Empire was not stable. The amount of concessions given to the Venetians varied over time and other Italian cities, such as Genoa, were also given certain priviledges. See @mcneillVeniceHingeEurope2009, p. 37; @lockFranksAegean120415002014, pp. 137- 140.] While much of the former Byzantine territory was doled out to various individuals, Venice obtained control of Durazzo, Corfu, Modon (modern Methoni), Coron and Cerigo (modern Kythera) by 1207, Euboea by 1209, and later began to take control of Crete in 1211.^[@mcneillVeniceHingeEurope2009, p.32; @darbyMedievalTurkishGreece1964, pp. 66-68.] Venice held Modon, Coron, Euboea and Crete for over 200 years.^[A collection of Venetian documents about Coroni and Methoni (@nanettiDocumentaVenetaCoroni1999) vividly illustrates Venetian rule in their colonies. Crete was held by the Venetians for over 400 years.] After 1204, the Peloponnese was ruled by various nationalities: Franks, Flemings, Piedmontese, and finally the Navarrese Company in 1383.^[@darbyMedievalTurkishGreece1964, pp. 61-63; @lockFranksAegean120415002014; @millerLatinsLevantHistory1908; @jacobyByzantiumLatinRomania1989; @angoldGreeksLatins12041989; @luttrellLatinsLifeSmaller1989; @balardGenoeseAegean12041989.] The resurgent Byzantine Empire conquered the Morea in 1432, but lost it to the Ottoman Turks by 1461.^[@darbyMedievalTurkishGreece1964, pp. 62-63.] From 1377 on, various castles had been sold, given or leased to the Venetians in an attempt to keep them out of Greek or Turkish control.^[@lockFranksAegean120415002014, p. 160. Nauplia and Argos in 1388; Naupaktos in 1407; Patras leased in 1408; Navarino in 1423; Monemvasia in 1463.] With the exception of Cyprus and the various Venetian holdings, there were no remaining Latin possessions in Greece.

After the First Veneto-Turkish war of 1463-79, in which Venice briefly held the Morea, the Venetians slowly lost possession of Greek territories to the Turks. By the 17th century all that remained was Crete, six of the seven Ionian islands, Tenos, Corfu, Butrinto, and Parga.^[@darbyMedievalTurkishGreece1964, p. 82; @millerLatinOrient1920, p. 403; **TODO: find this ref** Slot 1982, pp. 82-116, 176-177.] The entire island of Crete, Venice’s longest-standing possession in the Levant, was lost to the Ottoman Empire in the Cretan war (1645-69) except for the fortresses of Grabusa, Suda, and Spinalonga.^[@darbyMedievalTurkishGreece1964, pp. 83-84; @lockFranksAegean120415002014, p. 160; **TODO: find this ref** Slot 1982, pp. 162-192.]

In the late 17th century, the Ottoman Turks suffered military defeats and the Venetians gained a foothold in Greece once more. In 1683, the Turks were defeated at Vienna and effectively stopped from conquering more of Europe.^[@millerLatinOrient1920, p. 403.] To ensure that the Turks would not be able to continue their conquests in Europe, a “Holy League” was formed by the Holy Roman Emperor, Poland, and Venice with the blessing of Pope Innocent XI. Venice immediately declared war on the Turks and placed Francesco Morosini, who had defended Crete in the Cretan war, in charge of the army.^[@millerLatinOrient1920, p. 403; @mckenzieTurkishAthensForgotten1992, p. 18.] The Ottoman Turks were distracted from Greece at this time, because they were also at war with Russia.^[@millerLatinOrient1920, p. 406.]

In 1685, Morosini began military operations in the southern Peloponnese with an army comprised of mercenaries from various European nations.^[@millerLatinOrient1920, p. 404; @mckenzieTurkishAthensForgotten1992, p. 18.] During 1685, the Venetians gained Coron, Zarnata, Kelepha, and Kalamata in the southern Peloponnese. The rest of the southern Peloponnese and Argolid, with the exception of Monemvasia, was conquered during the 1686 campaign season. The entire Morea, except Monemvasia, which was not surrendered by the Turks until 1690, and Athens were under Venetian control.^[About the conquest of the Morea: @millerLatinOrient1920, pp. 404-409, 414; @mckenzieTurkishAthensForgotten1992, p. 18. The Venetian capture of Athens: @millerLatinOrient1920, pp. 406-409; @mckenzieTurkishAthensForgotten1992, pp. 18-19; @patonVenetiansAthens168716881940. It was at this time that the Parthenon was destroyed by the Venetian bombardment of Turkish fortifications on the Acropolis.] After a failed attempt to capture Euboea, in the winter of 1687, Morosini decided to abandon Athens and relocate the Greek inhabitants to other Venetian- controlled areas.^[The decision to abandon Athens was affected by an outbreak of the plague in Greece (@millerLatinOrient1920, pp. 412-413; @mckenzieTurkishAthensForgotten1992, pp. 20-21). The Athenians were opposed to leaving their property in Attica, but were promised land and other compensation when they reached the Morea **TODO: follow up on whether only Athenians with property moved** (@millerLatinOrient19201, p. 414; @mckenzieTurkishAthensForgotten1992, p. 21). When Morosini left Athens, he sent four lions scavenged from Piraeus to adorn the Arsenal in Venice (@millerLatinOrient19201, p. 413; @mckenzieTurkishAthensForgotten1992, p. 22).] The Athenians left the city on March 24, 1688 for the island of Zante, various parts of the Morea, or - the preferred option for the Athenians - nearby Salamis.^[@millerLatinOrient19201, pp. 413-414; @mckenzieTurkishAthensForgotten1992, p. 21.] In 1699, the Treaty of Karlowitz formally ended hostilities and gave possession of the Morea to the Venetians.^[@darbyMedievalTurkishGreece1964, p. 84; @millerLatinOrient19201, p. 417]

The Ottoman Empire declared war on Venice in 1714, after Russia had been defeated. By October, 1715, the entire Morea and the three Venetian bases on Crete had been lost to the Turks. The Morea was quickly conquered by the Ottoman Empire in part because most fortifications were surrendered by the Venetian commanders, with little or no resistance.^[@millerLatinOrient19201, pp. 424-426. For an account from the Ottoman side, see @brueJournalCampagneQue1870. ] **TODO: explore whether Greek hatred really led to rapid defeat** One reason for the rapid advancement of the Ottoman Turks was the Greek hatred of Venice’s policies. The problems between the Latin Catholic church, which the Venetians insisted have authority over the Morea, and the Orthodox Patriarch, oppression of any industries that would be in competition with Venice, and the quartering of soldiers in Greek households, made the Greek inhabitants of the Morea eager for the return of the Turks.^[@darbyMedievalTurkishGreece1964, p. 84; @mcneillVeniceHingeEurope2009, pp. 220-221.] Peace was negotiated between the Turks and Venetians in 1718 by the treaty of Passarowitz, which left Venice only with Kythera, Antikythera, Butrint (Albania), Lefkas, Prevesa and Vonitza.^[@darbyMedievalTurkishGreece1964, p. 85; @millerLatinOrient19201, p. 426.] The Morea remained under Ottoman domination until the 19th century when the Greek War of Independence brought political autonomy to Greece.
