# Venetian Cadasters for Vostizza {#cadasters}

**TODO: revise and expand text**

In order to identify which land was deserted and also to create a system of taxation based on ownership of land, the Venetians immediately began a program of land-survey in 1687. Three directors were appointed to take charge of the survey of the Morea (sindici e catasticatori): Marin Michiel, Gierolimo Renier, and Domenico Gritti.^[@toppingCoexistenceGreeksLatins1976, p. 310; @toppingPREMODERNPELOPONNESUSLAND1976, pp. 92-93. Renier died during the first year of work, leaving the burden of the land survey to fall upon Michiel and Gritti. The more detailed Catastico Particolare for Vostizza was accomplished by Francesco Grimani.] The catastico ordinario, an account of each settlement in a territory, was completed for almost the entire Peloponnese by Michiel and Gritti. The catastico particolare, a listing of plots of land in each luogo, was only completed for the territories of Elis, Fanari, Karitaina, Argos, Vostizza, and Romania.^[@toppingPREMODERNPELOPONNESUSLAND1976, p. 96. The cadaster for Nauplion is discussed in @liataNayplioKaiEndohora2002.] The two land-surveys of Vostizza were submitted to the Venetian Senate in 1700.

**TODO: edit thesis text**
## Collection of Property Information
The Venetian administration of the Morea needed specific information about all property in Vostizza in order to collect taxes properly. To this end, each individual piece of property in the territory of Vostizza had an entry in the catastico particolare. The entries for fields were grouped by luoghi. Within the luogo, the fields were grouped by owner. All of the fields that were terreni “non-vineyard” were assigned an identification number which corresponded to a plot of land on the map of the luogo, and the area of each parcel was recorded according to three measurement systems – stremmata, Paduan feet, and Trevisan feet.112 Vigne (“vineyard”) parcels in the luogo were also listed with their identification number113 and the area of the parcel measured in zappade, as well as in the other three measurements used for terreni. In some cases, when the type of ownership (beneprobatum, non-beneprobatum, concessione, or church property) was the same for all of one owner’s parcels in a luogo, the type of land was specified at the bottom of the owner’s entry. The type of ownership of a parcel was also recorded on the luogo maps. A specific color was used to outline all parcels of a given type (rosso [“red”] for public land, giallo [“yellow”] for beneprobatum land, verde [“green”] for Beneprobatum vines, nero [“black”] for non-beneprobatum land, turchino [“blue”] for concessione, and pauonazzo [“purple”] for ecclesiastical land). The Venetians then had at their disposal information about the location of fields, who the owners were, the status of the land listed, and the area of fields.
The fields in each luogo were catalogued without regard to fields in other luoghi. In some cases, a person owned fields in more than one luogo. In such cases it is clear that information about these must not have been collected from the owner, because his name may be spelled differently in each. The information about ownership of land probably came from another source, such as the village headman or a priest.114


111 A.S.V. Grimani b.52/148.
112 Both Padua and Treviso were part of the Venetian terraferma by the 16th century A.D. (Cosgrove 1988, fig. 1, p. 255).
113 In most luoghi, a separate sequence of numbers was used for terreni and vigne. Only in a few luoghi were fields given identification numbers regardless of the type of land.
114 Kiel 1997.

## Villa Maps
**TODO: edit thesis text**
The Venetians were thorough in their recording of property in Vostizza. Each field in a luogo was recorded on a map of the luogo that was included with the lists of property included in the catastico particolare. The boundary of each field on the map was then traced in color, in order to indicate the type of land ownership (i.e., beneprobatum, non- beneprobatum, concession, and ecclesiastical land) and an identification number was assigned to it. A number on each field on the map corresponds to the entry for the field in the catastico particolare (Fig. 26).
Surveying property boundaries had been a well-practiced art among the Venetians for well over 100 years when they conquered the Morea. In the terraferma, surveyors had been creating maps that displayed property boundaries since the 16th century, usually in reference to irrigation projects.115 Cartographers such as Giacomo Gastaldo and Cristoforo Sorte served then as surveyors in the terraferma. Their work included the determination of field size and the rendering of their shape on maps, activities which were also used in the construction of the catastico particolare of Vostizza.116 By 1564, Venetian maps recorded property boundaries, such as in Fig. 27. The work of surveying fields in Vostizza would have been routine for Venetian surveyors.

115 Cosgrove 1988, pp. 254-257.
116 Cosgrove 1988, p. 257.
