## Vostizza Cadasters {#data}

## Villa Maps
**TODO: edit thesis text**
The Venetians were thorough in their recording of property in Vostizza. Each field in a luogo was recorded on a map of the luogo that was included with the lists of property included in the catastico particolare. The boundary of each field on the map was then traced in color, in order to indicate the type of land ownership (i.e., beneprobatum, non- beneprobatum, concession, and ecclesiastical land) and an identification number was assigned to it. A number on each field on the map corresponds to the entry for the field in the catastico particolare (Fig. 26).
Surveying property boundaries had been a well-practiced art among the Venetians for well over 100 years when they conquered the Morea. In the terraferma, surveyors had been creating maps that displayed property boundaries since the 16th century, usually in reference to irrigation projects.115 Cartographers such as Giacomo Gastaldo and Cristoforo Sorte served then as surveyors in the terraferma. Their work included the determination of field size and the rendering of their shape on maps, activities which were also used in the construction of the catastico particolare of Vostizza.116 By 1564, Venetian maps recorded property boundaries, such as in Fig. 27. The work of surveying fields in Vostizza would have been routine for Venetian surveyors.

115 Cosgrove 1988, pp. 254-257.
116 Cosgrove 1988, p. 257.
