## Cadaster Creation {#creation}

**TODO: edit thesis text**
## Collection of Property Information
The Venetian administration of the Morea needed specific information about all property in Vostizza in order to collect taxes properly. To this end, each individual piece of property in the territory of Vostizza had an entry in the catastico particolare. The entries for fields were grouped by luoghi. Within the luogo, the fields were grouped by owner. All of the fields that were terreni “non-vineyard” were assigned an identification number which corresponded to a plot of land on the map of the luogo, and the area of each parcel was recorded according to three measurement systems – stremmata, Paduan feet, and Trevisan feet.112 Vigne (“vineyard”) parcels in the luogo were also listed with their identification number113 and the area of the parcel measured in zappade, as well as in the other three measurements used for terreni. In some cases, when the type of ownership (beneprobatum, non-beneprobatum, concessione, or church property) was the same for all of one owner’s parcels in a luogo, the type of land was specified at the bottom of the owner’s entry. The type of ownership of a parcel was also recorded on the luogo maps. A specific color was used to outline all parcels of a given type (rosso [“red”] for public land, giallo [“yellow”] for beneprobatum land, verde [“green”] for Beneprobatum vines, nero [“black”] for non-beneprobatum land, turchino [“blue”] for concessione, and pauonazzo [“purple”] for ecclesiastical land). The Venetians then had at their disposal information about the location of fields, who the owners were, the status of the land listed, and the area of fields.
The fields in each luogo were catalogued without regard to fields in other luoghi. In some cases, a person owned fields in more than one luogo. In such cases it is clear that information about these must not have been collected from the owner, because his name may be spelled differently in each. The information about ownership of land probably came from another source, such as the village headman or a priest.114


111 A.S.V. Grimani b.52/148.
112 Both Padua and Treviso were part of the Venetian terraferma by the 16th century A.D. (Cosgrove 1988, fig. 1, p. 255).
113 In most luoghi, a separate sequence of numbers was used for terreni and vigne. Only in a few luoghi were fields given identification numbers regardless of the type of land.
114 Kiel 1997.
