# Landscape of Vostizza {#landscape}

TODO: revise text and add more info

<!-- Unedited M.A. text -->
The Venetian territory of Vostizza is located in the northern Peloponnese along the Gulf of Corinth (Fig. 1). The total land area of the Vostizza region according to Venetian surveyors is 149 square km (152,136 stremma and 349 tavole).11 The territory is bounded by the Gulf of Corinth to the north. The northern shore of the Gulf of Corinth is visible from most of the shore in the Vostizza territory.  

The primary city of the region is Aigion, named Vostizza Terra (town) in Venetian records. The perceived potential of Aigion as a harbor varies by source. According to the late 17th century traveler to the Morea, Bernard Randolph, the town of Aigion (Vostizza) did not have a port.12 Sir William Gell, writing in 1817, reported that “the anchorage is not safe with a northerly wind,” which implies that the town did have a dependable harbor.13 Colonel Leake in 1830 noted that the harbor at Aigion (Vostitza) was safer than the port at Patras, although it was very deep near the shore.14 The handbook for the British Army created in the 1940s described Aigion as the best harbor in the Gulf of Corinth.15

The terrain in the territory of Vostizza is mostly mountainous with a small coastal plain around the town of Aigion. The elevation of the land ranges from sea level to 1770 m above sea level.16 The plain of Aigion, between the Erineos and Selinous rivers, is wide and is cultivated today with vines and fruit trees (Fig. 2). To the east of Aigion, the mountains crowd the coastline, leaving only 400 yards (366 m) of plain between them and the sea.17 The primary mountains in the area are part of the Aroania Mountains and Mt. Marmati. The rivers of the region include, in addition to the Erineos and Selinous, the Vouraikos, Krathis, and Krios.18

The climate in Vostizza is typically Mediterranean with hot, dry summers and wet, cooler winters. Temperatures for the Peloponnese can range from 0° C in the winter to 48° C in the summer. The majority of rainfall accumulates during the winter months of November, December, and January.19 The vegetation of Vostizza, as determined by the climate, belongs to the True Mediterranean Region, southern zone.20 The foothills and mountain regions today are covered mainly with evergreen woods and maquis. Aleppo and stone pines are the most characteristic types of trees for the area.21 The land was more arid and had fewer trees than today in the early 19th century.22 The inventory of trees in the catastico ordinario for Vostizza shows that olives, grapes, mulberries, oranges, apples, quinces, figs, peaches, pears, plums, pomegranates, lemons, cherries, and almonds were all grown in the area in 1700. Since that time currants have become widely cultivated on the plain of Aigion.23




<!-- Footnotes -->
11 Dokos and Panagopoulos 1993, p. 6. This conversion to km2 is made under the assumption that the stremma consisted of 324 tavole, with a tavole equalling 3.02 m2. A Venetian tavole equalled 25 sq. piede (feet). A Venetian piede was 0.348 m (Zupko 1981, pp. xxx; 136, 283). See Davies 2004, appendix 2, pp. 113-116. The modern area of Aegiale, which is smaller than the Venetian territory of Vostizza, is 103 square kilometers in area (Ministère de L’Économie Nationale 1914, table D, p. vi.).
12 Randolph 1689, p. 3.
13 Gell 1817, p. 7.
14 Leake 1830, pp. 182-183.
15 Greece vol. I, pp. 48-49.
16 Dokos and Panagopoulos 1993, pp. 698-699.
17 Greece vol. I, pp. 48-49.
18 Greece vol. I, fig. 40.
19 Greece vol. I, pp. 89-92.
20 Greece vol. I, fig. 64, p. 109.
21 Greece vol. I, p. 108.
22 Grove and Rackham 2001, p. 185. 23 Greece vol. I, pp. 48-49.
