## Landscape During the Venetian Era (1685-1715) {#venetian-landscape}

**TODO: add text**



**TODO: edit M.A. thesis text**




#### Sources for Venetian Administration
**TODO: edit to change luogo to villa**
I draw upon five separate sources of information for this analysis of luoghi and settlements in Vostizza. The first source is a map of the territory of Vostizza that dates to 1700.92 The map shows the boundaries between the luoghi in Vostizza. The locations and designations of the settlements (i.e., villa, zeogolatio, machala) are also indicated on the map. The second source is the catastico particolare, which in part repeats information contained in the catastico ordinario, since the more detailed cadaster was created by supplementing the ordinary cadaster with information about property ownership, as described in Chapter 3.93 The third source is a list of village possessions that dates to 1698.94 This list includes the number of horses, gardens, orchards, olive and fruit trees, houses, grain mills, felt machines, animal huts, and towers in the recorded settlements. The fourth source consists of the records of tithe auctions for Vostizza from 1697 until 1700.95 This list of records may be used as a general indication, but not a direct indication, of the value of property and items in the villages in Vostizza, since the tithe amount was auctioned and its amount reflects how much people were willing to bid.96 The final source is the Grimani census, which contained the number of families and total population for the settlements in Vostizza.97 All of these sources provide information about how the Venetians organized Vostizza into various administrative units.


92 Kriegsarchiv B III a 121.
93 Dokos and Panagotopoulos 1993; A.S.V. Grimani b.81/56-279.
94 A.S.V. Grimani b.53/155.
95 A.S.V. Grimani b.52/148.
96 Davies 1996, pp. 81-85.
97 Pangiotopoulos 1985, pp. 231-289, esp. p. 279 for Vostizza; A.S.V. Grimani b.54/158.


#### Settlement Types in Vostizza
**TODO: edit thesis text**
Most of the differences between the Austrian Map, the catastico ordinario, and the catastico particolare involve minor differences in spelling. Of more interest are the differences in the status of settlements between the three sources (Fig. 13). The categories of settlements found in the cadasters and on the map include Villa (“inhabited villa”), Villa desabitata (“deserted villa”), Zeogolatio (“inhabited zeogolatio”), Zeogolatio desabitata (“deserted zeogolatio”), Monastero (“monasteries”), Mettochi (“mettochi”), and Machalade (“machalas”). Villas were settlements that may have been inhabited or deserted. The town of Vostizza was classified as a terre (town) which entailed more rights than a village, but for ease of analysis, the town of Vostizza (Aigion) is here included among the inhabited villas.
Monasteries and mettochi were settlements with property owned by the church. Mettochi were dependant settlements of monasteries. In the summary of population per age group for the province of Achaia included in the Grimani Census98, six monasteries are recorded, along with their total population, for the territory of Vostizza, but mettochi are not otherwise mentioned (Fig. 20).99 Also, two mettochi that appear in both the catastico ordinario and the catastico particolare, as well as on the map of the territory, are absent from the Grimani listing. This is an example of the relative unreliability of the Grimani census. It should also be said that places recorded as deserted in other records are simply not listed in the Grimani census, since they do not have an associated population.
The term machala is a term that was used exclusively to refer to four settlements in the luogo of Diacofto (GR33) and the luogo of Porouzia, Plessa, and Pirgo (GR35). The term machala, which is Turkish, is equated in the Venetian records with the Italian word contrada. Both terms mean neighborhood. The word contrada is also used in the description of Aigion in the catastico particolare to describe the five neighborhoods in the town. In the case of Diacofto, the luogo was composed of four smaller settlements, Castro, Piscopi, Vrostena, and Chierniza. The entire area was recorded under one name, Diacofto. The situation for Porouzia, Plessa, and Pirgo (GR35) is similar. The three settlements were called machala or contrada in the catastico ordinario and the catastico particolare and grouped into one luogo.
The final categories of settlement found in Vostizza, inhabited and deserted zeogolatii, are not fully understood. Some confusion exists among scholars as what the Venetians meant by a zeogolatio/seogolatio. Hamish Forbes in his analysis of the economy of Ermionidha in the Southern Argolid (Fig. 21) in the year 1700 studied Venetian cadasters for the area and the Grimani census.100 According to him a “seogolatio” was possibly “only seasonally occupied”101; he furthermore argues that the term specifically was used to refer to settlements used for seasonal cultivation of the land and not for pastoral activities.102 This argument revolves around Forbes’ notion that the words sevgolatio/zevgolatio and ziogolatio/giogolatio derive from Greek words meaning “to plow” (zevgharizo) and the Italian word in the Venetian dialect ziogo, which means yoke. The term boaria, which seems to be used interchangeably for seogolatio in the territorio of Romania, in which Ermionidha is located, is said to be derived from the Italian word for cattle, thus strengthening Forbes’s argument that zeogolatio/boaria were used for cultivation. Forbes strengthens his argument by observing that zeogolatio are found in villas in the Ermionidha area with large amounts of cultivated land, but not in villas with small amounts of cultivated land and large areas for pasture.103
Forbes’s definition of seogolatio/zeogolatio fits the data found in Venetian cadasters and in the Grimani census as these pertain to Ermionidha, but does it hold true for other areas of the Peloponnese? Other scholars have defined the term zeogolatio differently. Siriol Davies, for example, states in a glossary of terms in a recent article that a seogolatio is an “estate or private farm”, but in her dissertation (1996) the definition was more involved. In its glossary, a seogolatio is defined as a “large domain of crown or Church property, ceded for cultivation, often uninhabited.”104 In her most recent study, Davies tries to find a link between çiftliks – Ottoman estates in the area of Navarino that supported their owners financially – and the terms segolatio, boaria, and mettochi.105 The Ottoman cadaster dating to 1716 records more çiftliks then the number of zeogolatii, boarie, and mettochi recorded by the Venetians in their records.106 It appears from these data that the Venetians imposed their own classification system upon settlements in the Morea, sometimes recognizing that there had been an Ottoman çiftlik by recording the settlement as a zeogolatio or mettochi, but at other times calling a former çiftlik a villa.
In light of these observations, should Forbes’s assertion that seogolatio/boaria refer to almost exclusively to dependant settlements related to cultivation be accepted? Forbes’s claim can be tested most readily by looking at the spatial patterning of settlements recorded in the catastico ordinario for Vostizza (Fig. 22). From this map, we see that settlements defined as zeogolatii by the Venetians did not always occur in luoghi that had inhabited towns. Five luoghi contained only zeogolatii. Four of the five luoghi with only zeogolatii are very small in size and all have areas smaller than the mean size of luoghi for the territory (Fig. 23).
In her analysis of Venetian Navarino, Davies found that most çiftliks were found in coastal areas close to fertile plains (Fig. 24).107 This pattern also holds true for Vostizza if we equate zeogolatii with çiftliks. The zeogolatii in Vostizza are grouped in the northwest section of the territory near the coast, in the area of Vostizza that was described by the Venetians as the most fertile. Furthermore, the percentage of worked land that was given as concessione is high in the luoghi that contained zeogolatii (Fig. 25). It is obvious from looking both at the map of landownership types and the accompanying table that all luoghi that contained zeogolatii had at least a quarter of the area of land parcels in it given as concessione. I suggest that so much land in luoghi with zeogolatii was given as concessione because there was a need to replace the Turkish owners of çiftlik estates who had fled.108 With these facts in mind, it seems very plausible that the Venetians classified Turkish estates (çiftliks) as zeogolatii and were not referring to seasonally cultivated settlements. It is otherwise clear that the Venetians classified settlements with regard to their former status under Ottoman rule. Monasteries and their dependant settlements continued to be classified as they had been in the Ottoman period.
The organization of luoghi in Vostizza was probably not completed until at least 1700, as has already been noted. The four sources for the designations of the settlements, the Grimani census, the territorial map of Vostizza, the catastico ordinario, and the catastico particolare, differ in their classification of some settlements, although all date to 1700. The Grimani census varies the most from the other three sources; the classifications of seven of 57 settlements differ from that in the other sources. The other three sources are in much closer agreement. The catastico ordinario and the catastico particolare are the most similar sources, because the Venetians created the particolare from the ordinario.109 The differences between the four sources probably reflect variations either in the official definition of settlements, or how the particular administrator in charge of gathering data viewed a settlement.


98 Panagiotopoulos 1985, p. 267.
99 Panagiotopoulos 1985, p. 279.
100 Forbes 2000. See pp. 48-55 for his discussion of settlement types in the Venetian definition.
101 Forbes 2000, p. 48.
102 Forbes 2000, p. 53.
103 Forbes 2000, p. 49 table 4.3 and p. 53.
104 Davies 2004, p. 112.
105 Davies 2004, pp. 98-104.
106 Davies 2004, pp. 102-103, table 7.
107 Davies 2004, fig. 4, p. 101.
108 See Davies 2004, p. 100; 1994.
109 See my discussion of the creation of the various Venetian documents in Chapter 3 and in the next section of this chapter.

#### Pattern of Villas and Settlements in Vostizza
**TODO: edit M.A. thesis text**
The pattern of settlements and luoghi in Vostizza in 1700 was in part determined by features of the landscape and the natural environment. All of the zeogolatii and most of the other settlements were located in the northwest part of the territory, in the area considered to be most fertile by the Venetians.110 Deserted settlements were more common in the southern part of the territory where the terrain is rougher and where even today villages are widely scattered. The eastern part of the territory, especially in the luogo of Diacofto, also was characterized by a dispersed settlement pattern, probably because the terrain is rough in this area.

110 See Chapter 3, Vostizza, Cumari, and Cachu.
