## Boundaries of Venetian Vostizza {#venetian-boundaries}

#### Territorial Boundaries of Vostizza
The boundaries of the territory of Vostizza during the Venetian occupation are well- established. The catastico ordinario and catastico particolare that described resources in Vostizza each contained descriptions of the physical boundaries of the territory. A map of the entire territory dating to 1700 shows both the boundaries of the luoghi within Vostizza and the rivers that defined most of the border between Vostizza and the three surrounding territories of Patrasso, Calavrita, and Corintho (Fig. 18).88 Vostizza was bordered on the north by the Gulf of Corinth and, to the west and south, by Patrasso and Calavrita. To the east of Vostizza lay the province of Corintho.
The luogo of Potamia was included within the territory of Calavrita, although it was entirely surrounded by lands belonging to Vostizza (Fig. 19). Potamia was clearly marked as part of Calavrita by the indication “di Calavrita” on the 1700 map of the territory and in the catastico ordinario of Vostizza. It was, however, included among the luoghi of Vostizza in the catastico ordinario.
Porouzia (GR35) was not coterminous with any other part of the territory of Vostizza, since it was separated from it by Potamia. The descriptions of the luoghi of Potamia and Porouzia in the catastico ordinario do not explain why Porouzia was part of the territory of Vostizza and did not belong to Corinth farther east or Calavrita farther south.
Potamia
Questa confina à Tramontana principiando al Mare dal loco detto Cachi Scala confinando con la Villa Diacoftò, uà à Curcuglidi e Prino, Pefco, S. Thodoro, Existrato, Curmitalica, altra Existrata, e Orti Poria, da doue confinando per Ponente uà à Trupolithari, e Camnolacha, da doue per Ostro uà à Cochinù, Zonari, Turcomgnimata, aitouugni, e ua al fiume di Zarugla, mediante il quale confinando con la Villa Porouizza, et altre che esistono sotto lo stesso Confine ua al punto detto sto Camignari, da doue al Mare in loco detto stò tù Glichia, da doue per Leuante con lo stesso Mare confinando ritorna al loco detto Cachi Scala la doue principiò à confinare per Tramontana con la Villa Diacoftò.
This villa is bordered to the north starting at primarily by the sea by the place called Cachi Scala, adjoining with the Villa Diacofto, it goes to Curcuglidi and Prino, Pefco, S. Thodoro, Existrato, Curmitalica, the other Existrata, and Orti Poria, from where the border to the west goes to Trupolithari and Camnolacha, from where to the south it goes to Cochinu, Zonari, Turcomagnimata, Aitovugni, and goes to where the river of Zarugla, by means of this, which adjoinings with the Villa Porouizza, and others which have the same boundaries, goes to until the origin under the same border the place called Sto Camignari, from where (it goes to) the sea goes at the place called Sto tu Glichia, from where to the east adjoining the same with the sea, adjoins, it returns to the place called Cachi Scala where it started to the primary part to the border on the north with the Villa Diacofto.
Porouiza
Questa Villa è diuisa nelle Contrade, ò Machalade Porouiza, Pirgo, e Plessa, onde hà lo stesso Confine qual principia à Tramontana al Mare dal punto detto Sto Gliga, e confinando con la Villa Potamia uà al Fiume di Zarugla, mediante il quale con la stessa Villa confinando uà à Rechi Besdogni da doue confinando con il Territorio di Calaurita per Ponente uà à S. Zorzi, poi à S. Nicolò da doue à Sarachinovugni da questo confinando con lo stesso Territorio di Calaurita per Ostro uà à Sto Bugano sto Alogni, da doue alla valle detta Thelopotamo mediante la quale uà al Mare, con il quale Confinando ritorna al punto detto Sto Glica la doue principiò à Confinare per Tramontana con la Villa Potamia.
This villa is divided into an territory in the Contrade or Machalade of Porouiza, Pirgo, and Plessa, so that it has from where to the same boundary which to the north starts with is principally the sea from the point called Sto Gliga, and adjoining with the Villa Potamia goes to the river of Zarugla, by means of which, bordering the same villa, it goes to Rechi Besdogni from where bordering the boundary with the Territory of Calavrita in the west to S. Zorzi, it goes to S. Nicolo from where to Sarachinovugni from this (place) to this bordering with the same Territory of Calavrita to the south, it goes to Sto Bugano sto Alogni, from where to the valley called Thelopotamo by which means of which this, it goes to the sea, bordering which it returns with this area that borders going to the place called Sto Glica where it started to adjoins to the north primarily with the Villa Potamia.

87 Above n. 68.
88 The map is held in the Österreichisches Staatsarchiv, Kriegsarchiv, in Vienna, B III a 121.
