# Mapping and Analysis {#mapping}


## Phase 1: Exploratory Data Analysis
Originally, all mapping for this project was done using GIS, namely ArcGIS. In the first stages, exploratory data analysis was completed after data from the Venetian cadasters had been combined with their spatial locations digitized from the map of the territory. However, these spatial data could not be linked to other spatial data since the map was not properly georeferenced to real world coordinates, which was difficult owing to problems with matching up the map from 1700 with present-day locations. Most maps that were created were choropleth or included pie charts for each villa. The data at this point was within a Filemaker database with relational tables to connect data.

### Mapping
TODO: revise section from thesis below
TODO: incorporate footnotes
Both modern maps and a Venetian map of Vostizza dating to 1700 were used to create the layers in the GIS. Five map sheets that contain the territory of Vostizza65 were combined into a single map in Photoshop, and then added to the GIS. The latitude and longitude of the composite modern map was registered with the GIS program to facilitate adding modern data in the future.
Next, the Venetian map of the territory of Vostizza in 170066 was scanned and added to the GIS. Once added, the 1700 map was put into proper spatial position through a process called “rubber sheeting.” In rubber sheeting, a map with an unknown coordinate system, such as the 1700 map, is placed on a map with known coordinates, in this case the modern map, by connecting the same points on each map. Once this process was accomplished for the Venetian map of Vostizza, the territory was approximately in the correct position (Fig. 6). As is clearly shown in Fig. 6, the Venetian map does not entirely match the modern map. This incongruity between the modern map and 1700 map is a result of mapmaking techniques of the early 18th century.67
After the Venetian map of Vostizza was positioned properly, new layers were created by digitizing features from the map. The boundaries of the territory and each luogo, as well as the positions of rivers and settlements were all digitized using a method called “heads up” or “on the fly” digitizing. The two names for this type of digitizing refer to the fact that the process takes place on the computer screen, rather than using a digitizing tablet. Four layers were created using heads up digitizing. Two polygon layers, one only of the territorial boundaries of Vostizza (Fig. 7) and the other of the boundaries of the luoghi (Fig. 8) were made.68 The rivers were digitized into a polyline layer (Fig. 9) and the settlements were placed in a point layer (Fig. 10). This completed the spatial additions to the GIS project.


65 These maps were created by the Hellenic Military Geographical Service. All are in the 1:50,000 m series. Aigion (022), Amygdalea (035), Chalandritsa (377), Dervenion (089), and Navpaktos (233).
66 This map is located in the Kriegsarchiv of the Austrian State Archives in Vienna (B III a 121); see Katsiardi-Hering 1993, p. 301.
67 For more information about the spatial relationship between Venetian maps ca. 1700 and modern maps see Wagstaff and Chrysochoou-Stavridou 1998.
68 The luogo (pl. luoghi) is a term I have coined from Italian to describe the unit composed of a settlement or settlements and the land belonging to those settlements.

### Database
The basic data about Vostizza in 1700 are recorded in the catastico ordinario and catastico particolare for Vostizza.69 Three databases were created from the general and detailed cadasters. Information from the catastico ordinario about each of the 34 luoghi in the territory was placed into a database named “Luoghi.” The data in the database “Luoghi” include information about number of houses, number of fruit and nut plants, and animals, and amounts of land under cultivation for each luogo (Fig. 11; Appendix 1 includes a description of all fields in the “Luoghi” database).
A second database for each separate agricultural field called “Property,” records the owner, type of ownership (public, beneprobatum, concessione)70, and amount of land (Fig. 12; Appendix 2 includes a description of all fields in the “Property” database). The Venetians recorded the land area with more than one measurement system. Vineyards are recorded by zappade, stremma, Campi Trevisan, and Campi Paduan.71 Other fields (terreni) omit measurements in zappade. Each measurement has been converted into square meters in the database.72
The third database – “Settlements” – corresponds to the point layer Settlements. The information in this database includes the name and designation of each settlement from the Venetian map of Vostizza, catastico ordinario, catastico particolare, and the Grimani census (Fig. 13). This database is used to illustrate the differences among the four sources in designations for settlements.


69 Dokos and Panagopoulos 1993; A.S.V. Grimani b.81/17-33 and b.81/56-279.
70 The categories of Venetian property ownership are defined in Chapter 5. The reader is referred to the Glossary for a short definition of the various Venetian terms used in this thesis.
71 The zappade is an areal unit of measurement for vineyards used in Greece. Stremmata are also Greek units of measurement for areas of land. The Trevisan and Paduan systems of areal measurement both used basic units called tavola, but of different sizes. See Zupko 1981, for differences in measurement between cities in Italy. In practice, the Trevisan and Paduan systems were often modified according to circumstance. See Topping 1972, esp. p. 78, Forbes 2000, and Davies 2004 for interpretations of Venetian land measurement in the Morea.
72 The size of the stremma employed in the Peloponnese during the Ottoman and Venetian periods has been a matter of controversy. See Davies (2004, pp. 113-116, esp. p. 114), who suggests that it was equivalent to 1889.37 m2 (for 625 tavole). Calculations based on the Vostizza cadastre, examined in this thesis, confirm that Venetian administrators imagined it to be equal to 1889.37 m2.



## Phase 2: Statistical Analysis
The difficulty with georeferencing the Venetian map to real-world coordinates was overcome in the next phase of the mapping using Erdas Imagine. Using trial and error of matching locations on the coastline and settlement locations in the interior with present-day villages, a reasonable georectification was achieved. From this georeferencing, the villas, rivers, and settlements were again digitized. Although other sources of spatial data could now be added to the analysis, no further analysis was completed along this vein. Instead, better choropleth maps (without any pie charts) were created that displayed the results of the contingency table analysis. The Filemaker database tables were exported to csv format and often opened in Excel. The tables in this format were also joined to the appropriate spatial data layers in ArcGIS and later QGIS.

## Phase 3: Advanced Analysis and Interactive Mapping
The current phase of mapping and analysis is the most ambitious yet. Planned analyses include least-cost path analysis between locations to analyze travel between villas, clustering analysis on the villas to look for patterns, and creation of interactive maps and story maps using leaflet.js.
